# Specify your own password for Grafana UI here
adminPassword: automate-all-the-things

ingress:
  enabled: true
  annotations: {    
    kubernetes.io/ingress.class: alb,
    alb.ingress.kubernetes.io/scheme: internet-facing,
    alb.ingress.kubernetes.io/target-type: ip,
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP,
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15',
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5',
    alb.ingress.kubernetes.io/success-codes: '200',
    alb.ingress.kubernetes.io/healthy-threshold-count: '2',
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  }
  hosts: []
  
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server # Name of the k8s service and it's port. In this case port is 80 which is default
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki-stack:3100 # Name of the k8s service and it's port
      access: proxy

dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

dashboards: # Commented dashboards are outdated and must be fixed manually
  default:
    # clusterMonitoringForKubernetes: # https://grafana.com/grafana/dashboards/10000-kubernetes-cluster-monitoring-via-prometheus/
    #   gnetId: 10000 
    #   revision: 1
    kubernetesViewsGlobal: # https://grafana.com/grafana/dashboards/15757-kubernetes-views-global/
      gnetId: 15757
      revision: 30
    kubernetesViewsNodes: # https://grafana.com/grafana/dashboards/15759-kubernetes-views-nodes/
      gnetId: 15759
      revision: 19
    # kubernetesSystemAPIServer: # https://grafana.com/grafana/dashboards/15761-kubernetes-system-api-server/
    #   gnetId: 15761
    #   revision: 13
    # kubernetesSystemCoreDNS: # https://grafana.com/grafana/dashboards/15762-kubernetes-system-coredns/
    #   gnetId: 15762
    #   revision: 13
    kubernetesViewsNamespaces: # https://grafana.com/grafana/dashboards/15758-kubernetes-views-namespaces/
      gnetId: 15758
      revision: 24
    kubernetesViewsPods: # https://grafana.com/grafana/dashboards/15760-kubernetes-views-pods/
      gnetId: 15760
      revision: 20
    nodeExporterFull: # https://grafana.com/grafana/dashboards/1860-node-exporter-full/
      gnetId: 1860
      revision: 31
    # lokiKubernetesLogs: # https://grafana.com/grafana/dashboards/15141-kubernetes-service-logs/?tab=revisions
    #   gnetId: 15141
    #   revision: 1
    # argocd: # https://grafana.com/grafana/dashboards/14584-argocd/
    #   gnetId: 14584
    #   revision: 1
    # awsElbApplicationLoadBalancer: # https://grafana.com/grafana/dashboards/650-aws-elb-application-load-balancer/
    #   gnetId: 650
    #   revision: 8
